### ISSUE TITLE
Support for Jest integration

### ISSUE THREAD

**Issue by cronin4392** [oddbird/true#108]
Hello,

I am curious if the library could integrate with [Jest](https://facebook.github.io/jest/) testing framework? Jest uses a very similar syntax to Mocha. When I attempted to use with Jest I get the message: 

```
Test suite failed to run

    Your test suite must contain at least one test.
```

I was planning on looking into the source code and attempting a PR.

**Comment by mirisuzanne** [comment]
I don't know much about how the integrations work (or Jest), @carljm and @davisagli might know. I'd love a PR if one is required!

**Comment by cronin4392** [comment]
Thank you @mirisuzanne. A note for other contributors, I used the mocha integration code. Jest uses `describe` and `it` as well. The true tests do run however Jest does not detect it as an integration test and gives me that error above.

**Comment by davydog187** [comment]
The issue is that jest thinks you haven't declared any tests. You can get it to work but putting a "dummy" test in your entry point.
