### ISSUE TITLE
How to set up gulp without the JS shim

### ISSUE THREAD

**Issue by chrisopedia** [oddbird/true#110]
Wondering if there is a way to run sass-true in gulp without having to run the test-setup.js as follows:

```javascript
// tests/setup.js
const sassTrue = require('sass-true');
const glob = require('glob');
```
```javascript
// Run tests
glob.sync( 'src/styles/**/tests/_*.scss' ).forEach(( file ) =>
	sassTrue.runSass({ file: file }, describe, it)
);// gulpfile
const mocha = require('gulp-mocha');

gulp.task('sass-true', () =>
	gulp.src('tests/setup.js', {
		read: false
	})
	.pipe(mocha({
		reporter: 'mochawesome',
		reporterOptions: {
			reportDir: '.mochawesome',
			reportFilename: 'sass-true'
		}
	}))
);
```

**Comment by jgerigmeyer** [comment]
@chrisopedia Can you provide a bit more context for what you're trying to achieve? `gulp-mocha` requires a .js file passed directly to it, so True works by setting up your tests in that JS file and then running it with Mocha. As far as I'm aware, there isn't a good way to combine it such that the sass files are run through True directly from the gulpfile.

**Comment by chrisopedia** [comment]
I guess I was hoping to pass a glob or SCSS files directly to the `gulp.src()` and avoid the shim

**Comment by jgerigmeyer** [comment]
That should be possible if you want to compile True as pure Sass, without Mocha. I think that's possible, but loses a few features; @mirisuzanne can probably speak to that better? If you want to use Mocha, I don't know of a way around the shim JS file.

**Comment by mirisuzanne** [comment]
@chrisopedia All the compilation is pure Sass. What Mocha provides is parsing of the results, including comparison of output tests. Without Mocha, you would have to compare output-tests manually. When I'm in that situation, I commit the output to version control, and use `diff` to catch any changes. If you're ok with that, you can run True without the shim.

**Comment by chrisopedia** [comment]
Fair enough, @mirisuzanne.  Thanks so much for the work on this.
