### ISSUE TITLE
Assert @errors

### ISSUE THREAD

**Issue by diego-codes** [oddbird/true#118]
I wonder if there is a way to assert errors thrown. Here is what I was imagining:

**`test.scss`**
```scss
@import "true";
@import "my-function";

@include describe("Throw example") {
  @include it("will throw an error") {
    @include assert-throws(error-func(), "This is an expected error message");
  }
}
```

**`my-function.scss`**
```scss
@function error-func () {
  @error "This is an expected error message";
}
```

So the test should pass if there was indeed an error thrown and the actual error message matches the expected message.

This is more of a question than a feature request at this point. It may not be feasible to achieve if it's not possible to render past the error-throwing test.

**Comment by mirisuzanne** [comment]
Sadly, that's not possible. Sass `@error` calls stop the compiler, so we have no way to capture them and continue parsing. See #92 for the best workaround we've found. That's also the technique we use for [testing True](https://github.com/oddbird/true/search?utf8=%E2%9C%93&q=_true-error&type=). Hope that helps!

**Comment by diego-codes** [comment]
Thanks @mirisizanne for the workaround!
