### ISSUE TITLE
Module not found: Error: Can't resolve 'fs' in etc.

### ISSUE THREAD

**Issue by CharlieGreenman** [oddbird/true#125]
Using Mocha/Karma + Jasmine, with the following code: 

```
const path = require('path')
const sassTrue = require('sass-true')
const glob = require('glob')

describe('Sass', () => {
  // Find all of the Sass files that end in `*.spec.scss` in any directory in this project.
  // I use path.resolve because True requires absolute paths to compile test files.
  const sassTestFiles = glob.sync(path.resolve(__dirname, '**/*.spec.scss'))

  // Run True on every file found with the describe and it methods provided
  sassTestFiles.forEach(file =>
    sassTrue.runSass({ file }, describe, it)
  )
})

```

I am receiving the error: `Module not found: Error: Can't resolve 'fs' in` for numerous packages. My file is called `scss.spec.ts` (and therefore is a Typescript file). 

I have installed the following packages: 
`npm install --save-dev sass-true node-sass jest glob` 

Feel free to let me know if there is anything I am missing out on. Thank you, this is a fantastic project, and likewise, your time is more than appreciated.

**Comment by jgerigmeyer** [comment]
@CharlieGreenman It's likely that the error here is in one of your test files or one of the Sass files being imported (maybe related to https://github.com/isaacs/node-glob or https://stackoverflow.com/questions/47020061/module-not-found-error-cant-resolve-fs-with-webpack?). Can you provide a stripped-down example (preferably in a GitHub repository) that triggers the error?

**Comment by CharlieGreenman** [comment]
@jgerigmeyer I can do that. Will provide a repo asap, no later than tonight.

**Comment by CharlieGreenman** [comment]
@jgerigmeyer The following repo has been created: https://github.com/CharlieGreenman/MonoAngularPixel

This issue can be see on master. Thank you.

**Comment by jgerigmeyer** [comment]
@CharlieGreenman Thanks! The repo is very helpful for tracking this down.

In short, your `scss.spec.ts` file is written to be executed in node (using e.g. node-glob), but your karma runner is executing the test files in Chrome. True uses `node-sass`, and isn't currently written to be run in a browser context.

If you bypass karma and run `jasmine libs/scss.spec.ts` (or `./node_modules/.bin/jasmine libs/scss.spec.ts`, depending on whether you have Jasmine installed globally), the Sass test executes as expected.

**Comment by CharlieGreenman** [comment]
@jgerigmeyer the thanks is all mine. This is a fantastic repo, really the first of it’s kind, and I’m excited to deep dive into it. If there is a place where I can dedicate money towards this repo, by all means, feel free to let me know. I strongly believe in it. Thank you.

I am going to go ahead and delete repo I created for this ticket. If you are reading this, consider it deleted.

**Comment by CharlieGreenman** [comment]
Also, might add a or for documentation, telling people about the above. Also I noticed inconsistencies within documentation in three places. Thank you.

**Comment by jgerigmeyer** [comment]
PR for doc improvement would be most welcome!

**Comment by CharlieGreenman** [comment]
@jgerigmeyer next time will have time for documentation will be May 27th. Will dedicate 1.5 hrs. then :)
