### ISSUE TITLE
Confusing output

### ISSUE THREAD

**Issue by damienwebdev** [oddbird/true#136]
I was writing some simple tests to confirm my suspicions about how some of the core sass functions work and I ran into the following:

```scss
@include describe('a simple test') {
    @include it('tests stuff') {
        @include assert-equal(
            str-slice("index", 1, 0),
            "    "
        );
    }
}
```

```
1) Sass messing about tests stuff
  Message:
    AssertionError [ERR_ASSERTION]: tests stuff ("[string] " assert-equal "[string] ")
  Stack:
    error properties: Object({ generatedMessage: false, code: 'ERR_ASSERTION', actual: '[string] ', expected: '[string] ', operator: 'assert-equal' })
```

Obviously, the test's assertion is wrong, but the resulting output message about the return's actual vs. expected is rather confusing.

```
actual: '[string] '
expected: '[string] '
```

**Comment by damienwebdev** [comment]
@mirisuzanne I'd think the former is probably better, the latter is less clear about the underlying issue.

**Comment by mirisuzanne** [comment]
@damienwebdev can you take a look at that PR, and see if it solves the issue for you?
