### ISSUE TITLE
Feature Request: Support for @media queries and breakpoints

### ISSUE THREAD

**Issue by shani-terminus** [oddbird/true#147]
I am confounded by how to test breakpoints.

Sample SCSS:
```scss
@mixin bp($point) {
    @if $point == 'layout-sm' {
      @media (min-width: 600px) and (max-width: 959px) {
        @content;
      }
    }
    @if $point == 'layout-gt-sm' {
      @media (min-width: 960px) {
        @content;
      }
    }
}
```
In the following example tests, both scenarios pass, though the second one is clearly designed to fail. If I add a value for content, eg `content: 'hello'`, I receive an expected value to be undefined. Expected returns nothing, and actual returns only the content with no @media query. Clearly the test isn't running as I imagined.
```scss
  @include test ('should correctly media query for "layout-sm"') {
    @include assert {
      @include output {
        @include bp(layout-xs);
      }
      @include expect {
        @media (min-width: 600px) and (max-width: 959px) {}
      }
    }
  }

  @include test ('should correctly media query for "layout-gt-sm"') {
    @include assert {
      @include output {
        @include bp(layout-gt-sm);
      }
      @include expect {
        @media (max-width: 599px) {}
      }
    }
  }
```

**Comment by mirisuzanne** [comment]
These are passing because both the mixin and the empty `@media` produce *no output* in Sass. No-output `==` no-output. In order for Sass to generate output, you have to include some `@content` in both examples:

```
@include test ('should correctly media query for "layout-sm"') {
    @include assert {
      @include output {
        @include bp(layout-xs) { --test: true; }
      }
      @include expect {
        @media (min-width: 600px) and (max-width: 959px) { --test: true; }
      }
    }
  }

  @include test ('should correctly media query for "layout-gt-sm"') {
    @include assert {
      @include output {
        @include bp(layout-gt-sm) { --test: true; }
      }
      @include expect {
        @media (max-width: 599px) { --test: true; }
      }
    }
  }
```

The `--test: true;` example can be replaced any valid properties/values.

**Comment by shani-terminus** [comment]
Thank you. I probably omitted too much code to accurately describe my problem. I am specifically asking about the`@media(min-width: 600px) and (max-width: 959px)` portion of the expect statement. It is not included in the actual output. 

Test and output in the screenshot
![sass-true-breakpoint-test-20190605](https://user-images.githubusercontent.com/44702601/58954572-8f798d80-8767-11e9-8caf-cba080918503.png)

**Comment by mirisuzanne** [comment]
Well, it's basically the same problem as above (and not related to True). Your `bp()` mixin requires nested content. You can nest it inside a selector like you have, but it will only wrap what you put inside it. For the output you want, you'll need to write either:

```scss
// selector can be outside
.test {
  @include bp(layout-gt-sm) {
    // but properties have to be nested
    content: 'hello';
    color: green;
  }
}

// selector can also be inside
@include bp(layout-gt-sm) {
  .test {
    content: 'hello';
    color: green;
  }
}
```

The `@content` declaration only works when you pass something into it.

**Comment by shani-terminus** [comment]
Fantastic!
The media query does not come back when the selector is outside, but it does when the selector is on the inside. Tests are working (and failing when expected) now! Thanks for your time.
