### ISSUE TITLE
support Sass module syntax

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/true#153]
See:
- https://github.com/sass/sass/blob/master/accepted/module-system.md
- https://sass-lang.com/documentation/modules
- npm `sass@1.23.0-module.beta.1`

This will be a breaking change, and require a major release.

**Comment by davidcmoulton** [comment]
Really appreciating this testing framework. Being able to unit sass functions and mixins is just awesome! 😀 

I'm looking into migrating our codebase to use sass modules as soon as we can. Is there any ball park forecast of when True might support them? I appreciate it's probably a lot of work.

**Comment by mirisuzanne** [comment]
@davidcmoulton I don't think you'll need to wait on us for that. The module system is designed to  be fully backwards compatible. Try it out, and let us know if you run into any issues!

**Comment by iamnewton** [comment]
@mirisuzanne so much thanks for all of the work you've put into this project and the numerous blog posts I've read about the new module system.  Loving working with it but having an issue getting `dart-sass` and `true` to work with `mocha` out of the box.

```
Error: Undefined mixin.
  ╷
1 │ ┌ @include test-module("function: best-contrast") {
2 │ │
3 │ │     @include test("it should return a color that has the best contrast when given 3 colors") {
4 │ │         $test: best-contrast(#8ce2d4, #fff, #000, 4.5, 4.5);
5 │ │         $expected: #4c7f76;
6 │ │
7 │ │         @include assert-equal(inspect($test), inspect($expected), "Return the best contrasted color");
8 │ │     }
9 │ └ }
  ╵
  test/_a11y.scss 1:1  @use
  test/test.scss 6:1   root stylesheet
```

Getting this as an error and wondering what I'm doing wrong.  Can provide more if that helps.

**Comment by mirisuzanne** [comment]
@iamnewton it depends on how you are doing the import - likely you are just missing the namespace on the mixins and functions:

```
@use '<path-to>/sass-true/sass/true'; // creates an implicit 'true' namespace
@use '<path-to>/contrast'; // I don't know where you define 'best-contrast', but it will also be namespaced by default

@include true.test-module(…) {
  @include true.test(…) {
    $test: contrast.best-contrast(…); // whatever namespace is created above
  }
}
```

you could turn off the namespace for either or both used modules, by adding `as *` to the end of an `@use` rule. That will pull the module functions/mixins/variables into the global namespace. Safest to choose one module or the other, in order to avoid potential naming conflicts.

**Comment by iamnewton** [comment]
Yeah, I figured it was something I was doing wrong.

```
// test/test.scss
@use "true";
@use "../src";

// Tests
@use "./a11y";
@use "./color";
@use "./lists";
@use "./math";
@use "./number";
@use "./string";

// Report
@include report;
```

This is my test scss; are you suggesting that I now have to import this file into each test file?

**Comment by mirisuzanne** [comment]
Ah, not exactly - but almost. :)

```
// test/test.scss
@use "true";
// (…no need to access the code being tested here…)

// Tests
@use "./a11y";
@use "./color";
@use "./lists";
@use "./math";
@use "./number";
@use "./string";

// Report (…use the namespace…)
@include true.report;
```

In each test module, you will need to import both `true` and the code to be tested. You can import the entire `../src` if you want, or the individual module you are testing (whatever file defines `best-contrast` in your example above).

So:
- no, you don't need to `@use` the test entrypoint file in each test-module
- you *do* need to `@use` both True and the code being tested in each module

We're starting to make this same update on Accoutrement. It's incomplete, but all the "utils" have been ported. See, for example, our [sorting utility test file](https://github.com/oddbird/accoutrement/blob/modules-core/test/utils/_sort.scss).

**Comment by iamnewton** [comment]
Oh my god!!! Thank you so much.  I got it all to work.
