### ISSUE TITLE
TypeError on sass-true `describe` mixin and incorrect report

### ISSUE THREAD

**Issue by geotrev** [oddbird/true#155]
Hello friends!

First issue here. I'm trying to set up `sass-true` for one of my projects. I'm using `node-sass` and a shim for jest. All of the setup seems to be working fine. Jest recognizes my shim and attempts to run the result.

However, as the title says, my setup keeps giving this error:

```
 RUNS  ./scss.spec.js  /undernet/node_modules/sass-true/sass/true/_messages.scss:34 DEBUG: 1 Test, 0 Passed, 0 Failed, 1 Output to CSS
 FAIL  /undernet/node_modules/sass-true/sass/true/_messages.scss:34 DEBUG: 1 Module, 1 Test, 1 Assertion  ● scss tests

       TypeError: describe is not a function

       7 |     const sassTestFiles = glob.sync(path.resolve(process.cwd(), "src/__tests__/*.spec.scss"))
       8 | 
    >  9 |     sassTestFiles.forEach(file => sassTrue.runSass({ file }, describe, it))
         |                                            ^
      10 |   })
      11 | })
      12 | 

      at describeModule (node_modules/sass-true/lib/main.js:76:3)
      at node_modules/sass-true/lib/main.js:50:5
      at arrayEach (node_modules/lodash.foreach/index.js:35:9)
      at forEach (node_modules/lodash.foreach/index.js:290:10)
      at Object.runSass (node_modules/sass-true/lib/main.js:49:3)
      at runSass (scss.spec.js:9:44)
          at Array.forEach (<anonymous>)
      at Object.forEach (scss.spec.js:9:19)
```

Here's my shim:

```
const path = require("path")
const sassTrue = require("sass-true")
const glob = require("glob")

describe("SCSS spec", () => {
  const sassTestFiles = glob.sync(path.resolve(process.cwd(), "src/__tests__/*.spec.scss"))

  sassTestFiles.forEach(file => sassTrue.runSass({ file }, describe, it))
})
```

The above works fine. I tried wrapping it one level deeper with an `it` but that didn't change the output. Also worth noting, if I remove the `describe` in the shim, jest thinks there's no tests and won't run `sass-true`.

A part of me thought maybe the `describe` being passed from Jest as part of the global scope wasn't being registered, but that's not the case here.

My scss spec file looks more or less like this:

```
@import "../../node_modules/sass-true/sass/true";

@include describe(...) {
  @include it(...) {
    @assert {
       // includes `output` and `expect` blocks 
    }
  }
}

@include report;
```

if I remove the `describe` here, the tests run fine, although the tests "pass" regardless of what is in my assertions. A separate issue perhaps, but it's hard to tell.

If I hit the file directly with `node-sass`, I get what looks like the correct output (although its missing pass/fail counts for some reason?):

```
/* # SUMMARY ---------- */
/* 1 Test: */
/* - 0 Passed */
/* - 0 Failed */
/* - 1 Output to CSS */
/* Stats: */
/* - 1 Module */
/* - 1 Test */
/* - 1 Assertion */
/* -------------------- */
```

Sorry, that's probably a lot of different problems all bubbling up as the TypeError at the beginning. Any ideas are appreciated! 🙏

**Comment by mirisuzanne** [comment]
I assume your Sass actually says `@include assert {…}` rather than `@assert {…}`?

The error does make me think it's an issue on the JS end, especially if you aren't able to reproduce it with a direct Sass compile. (Sass isn't able to run the output comparisons, which is why you don't get any pass/fail for "output to CSS" tests unless you use JS).

**Comment by geotrev** [comment]
Ah, yes, you're correct, it's `@include assert {`.

I'll recheck my JS. I was basing my setup off this guide: https://itnext.io/setting-up-sass-unit-testing-in-your-project-b683a2e8ac03

**Comment by mirisuzanne** [comment]
Let us  know - could be an issue in our JS as well? @jgerigmeyer would you need more info to look into this?

**Comment by et1421** [comment]
@geotrev You are missing brackets around describe and it:

```
sassTestFiles.forEach(file => {
  sassTrue.runSass({ file }, { describe, it });
});
```

Is working for me.

**Comment by geotrev** [comment]
Aha, thank you @et1421! I had given up on this. hah
