### ISSUE TITLE
Compare with decimal?

### ISSUE THREAD

**Issue by strarsis** [oddbird/true#159]
A particular function can return a decimal number `2.0`, but `sass-true` `assert-equal` still fails with an expected number of `2.0`. This is probably caused by rounding? Can rounding be taken into account, ensuring a specific precision?
Library and test code against: https://github.com/strarsis/sass-math-pow/blob/master/test/test.scss

**Comment by mirisuzanne** [comment]
We use Sass built-in comparisons, without any modification of the values. If Sass considers them equal, that's the result you'll get from True. We do provide the `$inspect` [parameter](https://www.oddbird.net/true/docs/api-assert-values.html#mixin--assert-equal) for use-cases where you want to test something more specific, I'm not clear if that solves your problem?

If you find a way to state the test you want in plain Sass, then it is possible to test in True. I built a [test on codepen](https://codepen.io/mirisuzanne/pen/XWbMBeY), where it looks like number comparisons are considered equal if there's no difference in the first 11 decimal places. Inspected/string-ified numbers must be equal up to 10 decimal places. I'm not clear if that's too exact for you, or not exact enough? If you need rounding, you can `round()` both input and output in your test…

**Comment by strarsis** [comment]
@mirisuzanne: Thank you for your answer. A fix/workaround to this precision issue was indeed rounding the actual number before comparing it.
