### ISSUE TITLE
Selectors orders with contains assert

### ISSUE THREAD

**Issue by Psixodelik** [oddbird/true#163]
Hello

Is it possible to force tests not to check specific selector sequences and their order?

There is such a code:

```
@mixin clear {
  %clearfix {
    *zoom: 1;

    &:before, &:after {
      content: " ";
      display: table;
    }

    &:after {
      clear: both;
    }
  }

  .container {
    @extend %clearfix;
  }
}
```

I check as follows:

```
@include contains(false) {
        .container {
          *zoom: 1;
        }
        .container:before, .container:after {
          content: " ";
          display: table;
        }
        .container:after {
          clear: both;
        }
      }
```

If you slightly change the original code, then the tests stop passing, although the meaning does not change. The order of the selectors changes, but in total they give the same result in terms of styles

```
@mixin clear {
  %clearfix {
	  *zoom: 1;

	  &:before {
		  content: " ";
		  display: table;
	  }

	  &:after {
		  clear: both;
		  @extend :before;
	  }
  }

  .container {
    @extend %clearfix;
  }
}
```

Test output:

```
+ expected - actual
    
         -.container {
      *zoom: 1;
    }
    
    .container:after,
    .container:before {
      content: " ";
      display: table;
    }
    
    .container:after {
      clear: both;
    }
         +.container {
      *zoom: 1;
    }
    
    .container:before,
    .container:after {
      content: " ";
      display: table;
    }
    
    .container:after {
      clear: both;
    }
```

Is there any way to disregard the order of the selectors?

**Comment by mirisuzanne** [comment]
You'll need individual `contains` for each selector block:

```scss
@include describe('clear') {
  @include it('generates...') {
    @include assert {
      @include output { @include clear; }
      @include contains { /* selector block */ }
      @include contains { /* selector block */ }
      @include contains { /* selector block */ }
    }
  }
}
```

**Comment by mirisuzanne** [comment]
Sorry, I didn't read that closely enough the first time.

The `contains` feature still requires an exact match, just not a match with the full output. You could combine multiple `contains` to create a more flexible test, but not one that is clever about selector ordering. True doesn't have that level of parsing knowledge about how CSS selectors work, or what would be "acceptable" reordering.
