### ISSUE TITLE
Feature Request: Allow CSS output when using test frameworks

### ISSUE THREAD

**Issue by oscarmarcelo** [oddbird/true#173]
AFAIK, CSS output (compiling to a `.css` file) only occurs if we run those tests through Sass compilation, but not when running through `sassTrue.runSass` using a test framework.

Is it possible to make `runSass` still output the test results to CSS files for a deeper, manual inspection?

**Comment by mirisuzanne** [comment]
I like this idea, since I often run both. @jgerigmeyer what do you think?

**Comment by jgerigmeyer** [comment]
@mirisuzanne Yeah, that makes sense, and wouldn't be difficult to add. At the minimum I think we'd need to add another True option for `outFile` (path where CSS file should be written). If we want to support sourcemap output too, we'd need additional `outMap` or something. You want to propose an API and I'll implement it?

**Comment by jgerigmeyer** [comment]
@mirisuzanne Is this still a priority? I don't remember where we ended up...

**Comment by mirisuzanne** [comment]
I don't think this is a priority. While it might be useful in some cases, you can already achieve this by running tests through both Sass and a test runner. I'm not sure an API would add much to that - we would basically be doing the same. So I'd probably just suggest people create an npm script to combine those commands if they want it.
