### ISSUE TITLE
assert-equal expected is not first argument

### ISSUE THREAD

**Issue by scottdavis** [oddbird/true#18]
First argument should be the expected value.

examples from other frameworks:

* http://ruby-doc.org/stdlib-2.0/libdoc/test/unit/rdoc/Test/Unit/Assertions.html#method-i-assert_equal
* http://junit.sourceforge.net/javadoc/org/junit/Assert.html#assertArrayEquals(char[], char[])
* https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertEquals
* https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertEqual

Its just a syntax thing but its something to consider for 2.0

**Comment by ericam** [comment]
Interesting. My approach was initially based on QUnit: http://api.qunitjs.com/equal/

And we're not alone:
- https://github.com/thejameskyle/bootcamp/blob/master/dist/core/mixins/_should.scss
- http://angular.github.io/protractor/#/
- http://jasmine.github.io/2.1/introduction.html
- http://mochajs.org/#assertions

I think we're in good company?

**Comment by ericam** [comment]
(several of those are BDD style, which I think we could easily add support for, as we've discussed.
