### ISSUE TITLE
Is there any way to test private members?

### ISSUE THREAD

**Issue by P233** [oddbird/true#181]
I just encountered an issue with testing the sass [private members](https://sass-lang.com/documentation/at-rules/use#private-members). I may not use any private members and just `@forward` some of the functions and mixins. But just wondering if there is any way to directly test private members? Thanks!

**Comment by mirisuzanne** [comment]
I don't think there's a good way, no. What I've done instead is create "private" modules – which are only used internally, and never forwarded to the end user.

**Comment by P233** [comment]
Got it. Thank you for the quick response. 👍
