### ISSUE TITLE
Can't find stylesheet to import: @use 'messages'

### ISSUE THREAD

**Issue by mauro1855** [oddbird/true#186]
Hi,

In my team we built a React application using node-sass, and we have some tests that we are running with sass-true 5.0 - everything is working great.
Today we decided to get rid of node-sass and move to sass, so we upgraded sass-true to 6.0.1 version. The application itself runs without problems, but now the sass-true tests don't run, and I have the following message:

```
Can't find stylesheet to import.
      ╷
    1 │ @use 'messages';
      │ ^^^^^^^^^^^^^^^
      ╵
      .../node_modules%5Csass-true%5Csass/config/_throw.scss 1:1  @forward
      .../node_modules%5Csass-true%5Csass/_true.scss 3:1          @use
      .../src/styles/_mixins.test.scss 1:1                                  root stylesheet
```

Could this be an issue with sass-true? Using SASS 1.32.13.
I tried using sass-true 5.0 version with the sass engine instead of node-sass, but no luck either.

**Comment by mirisuzanne** [comment]
Hi @mauro1855, I'm not able to reproduce this based on what you've provided. Can you show some more context for how you are using sass-true in your project? Are you able to create a reduced/simplified test-case that I can run here?

**Comment by mauro1855** [comment]
Hi @mirisuzanne, thank you for replying. I'll prepare a test repository in the next couple of days and let you know.

**Comment by mauro1855** [comment]
So, I was preparing the test repository and trying a couple more things, and I ended up finding the issue.

It is written in the sass-true documentation that we need to run Jest with the **node** environment, while my project uses jsdom, which is the react default (CRA/react-scripts). As soon as I changed the --env to node, the problem was fixed... but this config broke all my react tests.

So, essentially it seems the use of sass-true is rather incompatible with react projects using the react testing library, that uses a lot of jsdom functionality.
I tried using the ```@jest-environment node``` docblock to say that sass-true tests should use the node jest environment, but it unfortunately didn't work. 

I leave here my test repository anyway, in case you want to replicate the issue and try to find a way to make it work.

**Steps to reproduce:**
1. clone https://github.com/mauro1855/test-sass-true
2. ```npm install```` and ```npm test```

--> SASS tests fail

3. Change package.json and add ```--env node``` to the ```test``` script
4. run ```npm test```

--> SASS tests pass, but react tests fail

**Comment by jgerigmeyer** [comment]
> I tried using the `@jest-environment node` docblock to say that sass-true tests should use the node jest environment, but it unfortunately didn't work.

@mauro1855 It works for me locally if the docblock is at the _top of the file_:

```js
/**
 * @jest-environment node
 */

import path from 'path'
// @ts-ignore
import sassTrue from 'sass-true'
import glob from 'glob'

describe('SASS', () => {
  const sassTestFiles = glob.sync(path.resolve(process.cwd(), 'src/**/*.test.scss'))

  sassTestFiles.forEach(file => sassTrue.runSass({ file }, { describe, it }))
})
```

Alternatively, it might make sense to split your Sass tests into a different directory (or using a different naming pattern e.g. `*.sasstest.js`) so that they aren't picked up by the CRA test-runner, and then running them via a separate command (e.g. `jest --testRegex .sasstest.js --env=node`). But that depends on your preferred dev workflow, and whether your Sass relies on any of the CRA infrastructure.

**Comment by mauro1855** [comment]
@jgerigmeyer, you are totally right, it works if it's a the top of the file! In the jest documentation it is written explicitly _top of the file_, but I guess I looked straight at their example and thought it could be right before the tests. My bad!
Thank you for taking a look, now everything is fine.

As for your suggestion of splitting it, since it's working now I'd rather have all the tests suites running with react-scripts rather than having specific configuration to run certain tests. It's simpler imho.

Thank you.
