### ISSUE TITLE
Any css starting with [dir=rtl] is failing 

### ISSUE THREAD

**Issue by sissingclay** [oddbird/true#192]
Hi All, when the css selector starts with [dir=rtl] might be any attribute selector the test always fails.

css
```
[dir=rtl] .mdc-form-field > label,
.mdc-form-field > label[dir=rtl] 
```

Test 
```
[dir=rtl] **.test-output** .mdc-form-field > label,
.test-output .mdc-form-field > label[dir=rtl]
```

**Comment by mirisuzanne** [comment]
When writing output-css tests, we append selectors by default - but you can remove them to use your own selectors. See the `$selector` argument available on both the [`output()` and `expect()` mixins](https://www.oddbird.net/true/docs/api-assert-output#mixin--output).

**Comment by sissingclay** [comment]
Thanks, @mirisuzanne that works great.
