### ISSUE TITLE
Quoting strings

### ISSUE THREAD

**Issue by HugoGiraudel** [oddbird/true#22]
I am currently reviewing True's code to understand how it works, and it occurred to me it would be easier to read if strings were quoted. 

If you feel like it would be nice to have all strings quoted, I would be happy to submit a pull request doing just that, @ericam. :)

**Comment by ericam** [comment]
hmmmm, I tend to think of quotes as clutter — like adding `()` to all your lists. But if you made a PR, I probably wouldn't reject it. :)

**Comment by HugoGiraudel** [comment]
I'll give it a go. ;)

**Comment by HugoGiraudel** [comment]
Done in v3.

**Comment by ericam** [comment]
@HugoGiraudel I think you are confusing Susy and True. Maybe it is time for a True v3 though?

**Comment by mirisuzanne** [comment]
I did a final sweep. All strings should be quoted now. I wish we could lint for that.
