### ISSUE TITLE
Support `@at-root`

### ISSUE THREAD

**Issue by borisdamevin** [oddbird/true#222]
Hi,

Using the `@at-root` break the test workflow.

```
.grid {
  @at-root .grid-flow-col {
      // blablabla
  }
}
```

![image](https://user-images.githubusercontent.com/1703605/155699658-39f2a2e4-340d-4d1c-8fcd-eda2feac19d0.png)

**Comment by mirisuzanne** [comment]
Both the [`output`](https://www.oddbird.net/true/docs/api-assert-output#mixin--output) and `expect` mixins apply a wrapping selector by default. That's what's generating the `.test-output` class, which is the difference between your input and expected results. You can either use at-root on the expected result, or use the (true/false) `$selector` argument to turn off the extra selector.

**Comment by borisdamevin** [comment]
@mirisuzanne Work great, thank you!

I not sure to see thi option reference in documentations. :(

**Comment by mirisuzanne** [comment]
The selector argument is documented. I suppose we could flesh that out with more examples. Are you interested in contributing a PR for that?
