### ISSUE TITLE
Don't work with `glob` 8

### ISSUE THREAD

**Issue by borisdamevin** [oddbird/true#231]
Hi @mirisuzanne ,

With new `glob` 8.0 the test config doesn't work anymore.

| Package |  Version|
| --- | --- |
|`glob`|`8.0.3`|
|`sass-true`|`6.1.0`|

```
 ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:172:18)
      at node_modules/@jest/core/build/TestScheduler.js:300:17
      at node_modules/emittery/index.js:311:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/emittery/index.js:309:23)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.54 s
Ran all test suites.
```

**Comment by borisdamevin** [comment]
Hi @jgerigmeyer 

You can check here https://github.com/unsass/css/tree/update-glob _(branch "update-glob")_

The Github action is here : https://github.com/unsass/css/runs/6801074953?check_suite_focus=true

...but the error is not the same than local test :( .

**Comment by jgerigmeyer** [comment]
@borisdamevin That's a bug in Dart Sass: https://github.com/sass/dart-sass/issues/1712

If I downgrade Sass to v1.52.1, the tests pass on that branch for me.

**Comment by borisdamevin** [comment]
Ok with Sass 1.52.1 it"s work better but, I got something weird... @jgerigmeyer 

On local a got this error

![image](https://user-images.githubusercontent.com/1703605/172718318-2c74e5cc-9dc4-48ae-803e-06c7c921f34c.png)

But on the action https://github.com/unsass/css/runs/6802029864?check_suite_focus=true, all work good, so just my local (windows) bug without reason.
