### ISSUE TITLE
Release of new Dart API

### ISSUE THREAD

**Issue by coxrichuk** [oddbird/true#236]
I can see there are plans to release with the new Dart API

When is this estimated to be released?

**Comment by jgerigmeyer** [comment]
@coxrichuk Thanks for the reminder -- this had fallen off my radar. I'll take a look today and let you know.

**Comment by jgerigmeyer** [comment]
Hi @coxrichuk, I just released [v7.0.0-beta.0](https://github.com/oddbird/true/releases/tag/v7.0.0-beta.0) -- let me know if you run into any issues using it!

Assuming it works as expected, I'll do a full release sometime next week.
