### ISSUE TITLE
Using Jest `--config`

### ISSUE THREAD

**Issue by borisdamevin** [oddbird/true#252]
Hi, @jgerigmeyer @mirisuzanne 

When I launch Sass True 7.0 with Jest, and I specifiy the config file on script commande `jest --ci --config=\"__tests__/scss.spec.js\"` a error come: 

`ReferenceError: describe is not defined`

I try to wrap the config inside `describe('Sass', () => {});` but this still don't work.

**Comment by jgerigmeyer** [comment]
Hi @borisdamevin 

The [Jest `--config` option](https://jestjs.io/docs/cli#--configpath) is used to point to a Jest config file (e.g. `jest.config.js`), not to point to a test file. Can you point to sample repo or say more about what you're trying to accomplish?

**Comment by borisdamevin** [comment]
@jgerigmeyer I try to run Sass True in project when others *.spec.js exist for Cypress config.

**Comment by borisdamevin** [comment]
My savior!
