### ISSUE TITLE
NPM Workspaces

### ISSUE THREAD

**Issue by borisdamevin** [oddbird/true#262]
Hi, @mirisuzanne @jgerigmeyer 

I have a issue when I use `sass-true` with NPM Workspaces configuration. If I set tests files inside one packages folder and launch tests, `sass-true` don't find any `@use` import installed on root `node_modules` .

Any idea?

 Thank you.

**Comment by jgerigmeyer** [comment]
@borisdamevin Thanks for reporting! Would you be able to provide a minimal repo that reproduces this issue? That would be very helpful.

**Comment by borisdamevin** [comment]
Don't worry about that `loadPaths` fixe my problem.
