### ISSUE TITLE
Auto-detect `sass` vs `sass-embedded`

### ISSUE THREAD

**Issue by JoostKersjes** [oddbird/true#290]
I'm using `"sass-true": "8.0.0"` and incorrectly assumed that it would work with `"sass-embedded": "1.79.2"`.

The reason for replacing `sass` with `sass-embedded` is mostly for improved performance.

Error message:

```
 FAIL  test/sass.test.js [ test/sass.test.js ]
Error: Cannot find Dart Sass (`sass`) dependency.
 ❯ Object.runSass ../node_modules/.pnpm/sass-true@8.0.0/node_modules/sass-true/src/index.ts:112:13
 ❯ test/sass.test.js:13:44
     11|   });
     12| 
     13|   sassTestFiles.forEach((file) => sassTrue.runSass({ describe, it }, file));
       |                                            ^
     14| });
     15| 
 ❯ test/sass.test.js:13:17
```

**Comment by JoostKersjes** [comment]
The pipelines on our project did not fail for the change to replace `sass` with `sass-embedded`. I'm not exactly sure yet why they only started failing a day after the changes were merged, but that alone makes me think this is to do with caching.

**Comment by JoostKersjes** [comment]
Sorry for creating an issue in a rush. It turns out that this problem can be avoided by simply passing the `sass-embedded` as an option to True like such:

```js
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import sass from "sass-embedded";
import sassTrue from "sass-true";
import { describe, it } from "vitest";

describe("Sass", () => {
  const sassTestFiles = Object.keys(
    import.meta.glob("./**/*.test.scss", { eager: true }),
  ).map((relativePath) => {
    return resolve(dirname(fileURLToPath(import.meta.url)), relativePath);
  });

  sassTestFiles.forEach((file) =>
    sassTrue.runSass({ describe, it, sass }, file), // Pass sass-embedded to "sass" option
  );
});
```

**Comment by jgerigmeyer** [comment]
@JoostKersjes I think that's a good idea -- I've renamed this issue.
