### ISSUE TITLE
Feature Request: Support For Testing @errors

### ISSUE THREAD

**Issue by Undistraction** [oddbird/true#31]
Some kind of support for testing @errors is needed. 

I got around Sass's limitations when using Bootcamp by having anything under test trigger all errors through an error function:

From each library being tested I'd pass all errors through this function rather than throwing them directly:

```
@function throw-error($error, $message) {
  @if $under-test {
    @if not $error-thrown {
      $error-thrown: true !global;
      $last-error: $error !global;
    }
  } @else {
    @error "#{$error} #{$message}";
  }
  @return null;
}
```

Then before each assertion:

```
@include reset-errors();
```

Which resets the trapping of errors:

```
@mixin reset-errors() {
  $last-error: null !global;
  $under-test: true !global;
  $error-thrown: false !global;
}
```

This then allows me to compare the expected error with `$last-error` in an assertion. However this means manually calling `reset-errors()` to clean up every-time. Some kind of `before_all` hook would help with this, but as error testing is so fundamental, I think a fuller solution should be explored. This obviously overlaps with the request [here](https://github.com/ericam/true/issues/25) for a general reset hook which is also a necessary addition imho.

**Comment by ericam** [comment]
I'm not sure if I understand the full use-case here — would before/after options take care of it?

**Comment by Undistraction** [comment]
Some kind of per-test setup / teardown would be great, but given that there is no way of testing actual errors, and that errors are so fundamental to testing, I think it's worth thinking about adding some kind of simple API that helps libs test errors. In my example above, an `$under-test` switch can be flipped, causing the first error that would have been triggered to instead be stored to a `$last-error` variable. This can then be used in a test to check whether an error would have been thrown. Obviously this kind of scaffolding can be written in every lib, but I think it's worth considering building in some kind of support. That way libs (mostly) wouldn't need to worry about the mechanics of testing errors.

I'm not saying that my way is *the* way, though it has worked well with Bootcamp, but I think helping libs test errors could/should be in true's remit.

**Comment by mirisuzanne** [comment]
I'm still interested in this, but not sure how it would be done. I don't think it's possible in pure Sass, without help from either the tested library using special error functions internally (like above?), or the test-runner/parser hijacking errors. I'm open to ideas. If that mixin is built into the library, though, I'm not sure why we would also build it into True. Libraries can do this internally.

**Comment by mirisuzanne** [comment]
I implemented this in Susy 3. We could try adding it to True, but that would make True a shipped requirement for other libs, which doesn't sound ideal to me. I think it would be better to document the solution, and show others how to implement.

https://github.com/oddbird/susy/pull/600/commits/de0c473a95d99117475f1c023f17423803bb7e7b#diff-65a950017833d86c70a5e821971baa0fR50
