### ISSUE TITLE
Testing mixins with true-cli

### ISSUE THREAD

**Issue by utis** [oddbird/true#33]
Unless I'm horribly misunderstanding the intent and purpose of mixin tests, it seems that it's currently not working when tests are run with true-cli rather than mocha. Example file:

```
@import "true";

@mixin foo-bar($str) {
    color: $str;
}

@include test-module('An example') {
    @include test('foo-bar [mixin]') {
    @include assert('Do something') {
        @include input {
        .foo-bar {
            @include foo-bar(blue);
        }
        }
        @include expect {
        .foo-bar {
            color: blue;
        }
        }
    }
    }
}

@include report(true);
```

Running this test with true-cli yields:

```
/home/egoge/sites/modules/theme/modules/src/contrib/true/sass/true/_messages.scss:58 DEBUG: 1 Tests, 0 Passed, 0 Failed, 1 Output to CSS 
```

No actual comparision of output and expected output is taking place.

**Comment by ericam** [comment]
Yeah - `true-cli` isn't yet smart enough to parse the output, so it just let's you know they are there. You can compare them visually in the CSS. Our mocha integration is smarter, and will compare them for you. Always more to do! :)

**Comment by utis** [comment]
I see. Thank you, this confirmation gives me some peace of mind. So, I suppose if I want this but not mocha, I have to get me some ruby skills, eh? I guess a simple string comparision after whitespace normalization should be doable.

**Comment by ericam** [comment]
That's beyond me. :) @scottdavis built the CLI, and @carljm built the Mocha integration — maybe they would have some insight.

**Comment by carljm** [comment]
@utis The node-sass integration uses a real CSS parser to parse the output CSS to a syntax-tree format, and then render it back out as normalized CSS and do a string compare on that. I'm sure there are Ruby libs that can do the same. You might be able to get it to work using a hackier approach (just some simple whitespace normalization and assume everything else should match as-is), but personally I didn't have confidence that would do the right thing in all cases.

**Comment by utis** [comment]
Unless I'm completely misunderstanding something, we already have that with the sass gem. I browsed the spec a little and something like the following seems to get the data needed:

    # Putting this into true-cli
    ARGV.each do |file|
      sass_engine = Sass::Engine.for_file(file, {})
      # Use .to_tree rather than .render.
      tree = sass_engine.to_tree
      
      # Generate a "static CSS tree"
      Sass::Tree::Visitors::CheckNesting.visit(tree)
      result = Sass::Tree::Visitors::Perform.visit(tree)
      Sass::Tree::Visitors::CheckNesting.visit(result)
      result, extends = Sass::Tree::Visitors::Cssize.visit(result)
      Sass::Tree::Visitors::Extend.visit(result, extends)

      # Loop trough rule nodes
      result.each do |node|
        if node.is_a? Sass::Tree::RuleNode
          puts '---------------'
          puts 'The selector:'
          puts node.resolved_rules
          node.each do |child|
            if child.is_a? Sass::Tree::PropNode
              puts 'The property:'
              puts child.resolved_name
              puts 'The value:'
              puts child.resolved_value
            end
          end
        end
      end
    end

I'm a bit unsure how to proceed from here. I can read a spec and understand the code I'm looking at, but otherwise I've never dealt with ruby directly.

**Comment by carljm** [comment]
@utis I'm in the same boat as far as Ruby familiarity. It does look like the Sass gem has what you'd need, though. I'd guess I could probably take it from there to fix up `true-cli` for output comparisons, but I doubt I'll get to it since we're using node-sass on all our projects now.

**Comment by utis** [comment]
I went ahead and more or less translated the logic from lib/main.js to ruby:

https://github.com/utis/true/blob/iss33-tru-cli-mixins/bin/true-cli

I'll send you what I understand is  a "pull request" as soon as I have tested it some more. (I'm new to this on github.)

**Comment by mirisuzanne** [comment]
See PR #41 — needs updating to use the new output syntax.

**Comment by mirisuzanne** [comment]
Our Mocha integration is now much more feature-complete than the `true-cli`. Since node is also more reliable across dev environments, and easier to maintain, I'm tempted to remove the Ruby `true-cli` entirely in 3.0. 

@scottdavis - does that make sense to you?
