### ISSUE TITLE
lib/main.js: Dealing with media queries

### ISSUE THREAD

**Issue by utis** [oddbird/true#38]
For example:

    @import "true";

    $breakpoints: (mini: 200, medium: 900, large: 600);

    @mixin respond-to($break) {
        @media screen and (min-width: #{map-get($breakpoints, $break) * 1px}) {
            @content
        }
    }

    @include test-module('Media queries') {

        @include test('respond-to [mixin]') {
            @include assert('') {
                @include input {
                    @include respond-to(medium) {
                        color: blue;
                    }
                }
                @include expect {
                    @media screen and (min-width: 900) {
                        color: blue;
                    }
                }
            }
        }
    }

Yielding to the css output:

    /* # Media queries ---------- */
    /* respond-to [mixin] */
    @media screen and (min-width: 900px) {
      [data-module="Media queries"] [data-test="respond-to [mixin]"] [data-assert=""] .input {
        color: blue; } }
    @media screen and (min-width: 900) {
      [data-module="Media queries"] [data-test="respond-to [mixin]"] [data-assert=""] .expect {
        color: blue; } }

Naturally, the part that needs testing is the media query.

I came across this issue while rewriting true-cli to do the same thing as the mocha integration. I think this is rather important: As Sass can do more and more complicated things, people will naturally DO more and more complicated. And this is what necessitates true.  The Sass library I'm writing involves a lot of complicated mixins, most of them -- in this age of responsive webdesign -- involving a media query at some point.

I'm unsure of how to deal with this in a clean way. (In true-cli, that is) The least messy way I can think of right now would involve sorting the CSS into a hash table with the media query statement as its key. 
E.g.:

    # Pseudocode
    hash = hash table

    if selectors include .input
        then push [selectors, properties] to array in hash at key media-query-statement

    if selectors include .expect
        then  array = lookup media-query-statement in hash
        if there is no match
           then regard test as failed
        else
           properties = find seletor in array
           if there is no match, then regard test as failed
           else compare properties

Please advise!

**Comment by utis** [comment]
Wait! There's no guarantee that rules with .input in its selectors come before rules with .expect, right?

OTOH, parseSelector in lib/main.js and it's equivalent parse_selector that I've written for true-cli both return the selector info as a record type data structure. So, they could just check for a media query, look for the selector one level deeper and add the media query statement as an entry in that record, ready for comparision in the calling function.

Unless I'm missing something again, that would fit even fit better into the current logic.

**Comment by mirisuzanne** [comment]
We changed the output syntax to address this issue, but that also means your cli parser will need to be updated.
