### ISSUE TITLE
Error: Rule expected but ">" found.

### ISSUE THREAD

**Issue by teddybradford** [oddbird/true#42]
I get an error when I try to run a test on the following Sass mixin:

```scss
@mixin my-mixin($arg) {
  > * {
    font-size: $arg;
  }
}
```

It seems that the parser doesn't like the child selector. Is this not supported or am I missing something?

I'm using sass-true with mocha.

**Comment by ericam** [comment]
That's right, the parser is currently pretty limited in terms of selector manipulation. I'd love to get that fixed, but don't have a good proposal in mind at this point.

**Comment by mirisuzanne** [comment]
This should be fixed in the latest versions.
