### ISSUE TITLE
Project's URL (http://ericsuzanne.com/true/) redirects to http://www.miriamsuzanne.com/…

### ISSUE THREAD

**Issue by kaelig** [oddbird/true#48]
…instead of http://www.miriamsuzanne.com/true/

**Comment by ffoodd** [comment]
I think the actual URL is now http://oddbird.net/true/

**Comment by mirisuzanne** [comment]
If you mean the URL here on github, it's been fixed.

**Comment by mirisuzanne** [comment]
I mean, I fixed the project URL - I haven't fixed any redirect issues. I'll look into that.
