### ISSUE TITLE
Output number of assertions

### ISSUE THREAD

**Issue by CupOfTea696** [oddbird/true#57]
It would be nice to output the number of assertions made in the report.

**Comment by mirisuzanne** [comment]
You mean a total number of assertions across all your tests? Can you say more about why that would be helpful?

**Comment by CupOfTea696** [comment]
Yes, that's what I mean. And it's just an interesting stat really.

**Comment by mirisuzanne** [comment]
Great! Maybe something that can be turned on or off with a setting?

I'm open to a pull request, but this probably wont be a top priority for me.

**Comment by CupOfTea696** [comment]
Yeah a setting would be great. I might do a PR if I have some time.

**Comment by cuyaproductions** [comment]
Hi @mirisuzanne! I really like this project and would love to contribute. This issue seems like something I can do. Are you still wanting a PR for this?

**Comment by mirisuzanne** [comment]
@cuyaproductions sure! There's already a system in place for tracking tests, so you'll probably be able to tie into that same pattern. Let me know if you have questions. Thanks!
