### ISSUE TITLE
Fail on Error

### ISSUE THREAD

**Issue by Snugug** [oddbird/true#83]
I'm looking to use True with Node Sass (via Gulp) as part of my build pipeline. In order for this to work, though, I need True to throw an error if there are failures. This is needed as the typical workflow for automated testing assumes that if automated tests don't pass, the task running those tests errors out, and that error code signals to the continuous integration system that there are problems that need to be addressed. Simply using `@debug` or `@warn` doesn't throw an error code in Sass, and therefore doesn't cause CI to break.

I think there are two ways to resolve this:
* A mixin `fail-immediately`, to be set after importing true, which will set a global variable that, if present, will `@error` instead of `@debug` or `@warn` 
* A mixin `fail-on-error`, to be set after all tests in a file, which will take (in the background) a count of all test failures and, if the number of test failures is greater than 0, throw an error with the number of failed tests

**Comment by mirisuzanne** [comment]
Either would be easy to do. 

We also have Mocha integration for running the tests through node-sass/gulp, which should already error-out at the end. That also allows you to test mixin-output as well as function returns.

**Comment by mirisuzanne** [comment]
Closed by 2a95e5f — `$fail-on-error` is now an option in the `report()` mixin.
