### ISSUE TITLE
Unexpected rule type "font-face"; looking for module header

### ISSUE THREAD

**Issue by ProgrammingJoe** [oddbird/true#85]
In our SASS files we define the font-face using a bourbon mixin.

`@include font-face(...)`

And then assign that font to a variable and use it where need be.

Using `grunt mochacli` I am getting the error in the title. I imagine true is trying to interpret `@include font-face` font-face as a rule or a test? Do you guys have a workaround for this?

**Comment by mirisuzanne** [comment]
This is related to #74 (True doesn't like arbitrary output) and would require improvements to the parsing logic used for Mocha. @carljm do you want to weigh in on that? I'd love to see a PR for it, 'cause it's outside my skillset. :p 

The workaround right now is that you should only import Sass files without output, and only use mixins inside a test.

**Comment by mirisuzanne** [comment]
Resolved by #97
