### ISSUE TITLE
test-module vs test vs assert

### ISSUE THREAD

**Issue by mmellado** [oddbird/true#89]
I've been playing around with `true` for an open source project I'm building.

I really like the concept and the ease of use, however I'm a little confused about some parts of the behavior

I'm noticing that both `assert()` and `test()` take a comment as a parameter. However, when running my code with mocha, the comment from `test()` is the only one being outputed and the comment for the assert() is nowhere to be found.

Based on the code examples in the README I understand that each test file is a `test-module()` which then has a set of `tests()` which each have one `assert()` in it. It just feels weird because it seems like `assert()` isn't really doing much...

Somehow I feel like I'm not understanding the purpose of each of the functions which makes me feel I'm not fully understanding how to build my tests.

These is my example:

tests.js
```javascript
var path = require('path');
var sassTrue = require('sass-true');

var sassFile = path.join(__dirname, 'config.scss');
sassTrue.runSass({file: sassFile}, describe, it);
```

config.scss
```scss
// Adding the assertion framework
@import 'true';

// Test Dependencies
[library to be tested goes here]

// Tests
@import 'mixins/mixin-one.spec';
@import 'mixins/mixin-two.spec';
```

mixins/mixin-one.spec.scss
```scss
@include test-module('mixins/mixin-one.scss') {

  @include test('should render the output of mixin one with no parameters properly') {
    @include assert('this comment appears nowhere') {
      @include output {
        @include mixin-one();
      }

      @include expect {
        [output of mixin one with no params]
      }
    }
  }

  @include test('should render the output of mixin one with one parameter properly') {
    @include assert('this comment is also nowhere to be seen') {
      @include output {
        @include mixin-one(false);
      }

      @include expect {
        [output of mixin one with param here]
      }
    }
  }
}
```

With this being said, I'm wondering what the difference and purpose of each (`test()` and `assert()`) is. So far I've decided to remove the parameter form assert entirely as it's not even part of my mocha output but I'd like to get a better understanding of things.

I also realized that the library errors when I include a dependency that renders styles directly. (For example, I was trying to include the whole scss library as a dependency but since apart from all functions and mixins it also includes a reset file, it would throw an error, so now I'm only including the mixin and function files individually). I'm assuming this is an expected behavior. Can you explain a bit on why and how this works too?

Thanks!

**Comment by mirisuzanne** [comment]
Good questions! I think you may have reported a bug accidentally. :)

- The `test-module` mixin doesn't have to wrap an entire file, but can be used for any grouping of tests (even nested groups). That mixin, and description are for your own organization, as desired.
- The `test` mixin allows you to define what you consider a single test, with one or more assertions. Counting and error-reporting are handled at the `test` level. So two failed assertions in a single test will report as a single failure. But basically, tests are used to group assertions. In many cases, a test may wrap a single assertion, but it is still required. In my mind, the test description broadly explains the use-case being tested, while...
- The `assert` mixin is used to group a given `output` with the relevant `expect` results. Other assertion functions are available for testing non-CSS output (function returns, usually). Those include `assert-true`, `assert-false`, `assert-equal`, and `assert-unequal`. Assertion descriptions are optional, and are be output in the resulting CSS if you compile – but are not reported in the terminal unless the assertion fails. Use the assertion description to explain the desired behavior of a single assertion, if it's not already described clearly by the `test`. I mainly use them when a single test has multiple assertions. That's useful if I want to ensure both e.g. `type == map` and `length == 3` in the result of a single use-case.

In your case, ignoring the assertion-description makes sense, but the mixins still serve a purpose in describing what you want from True. If you do add assertion-descriptions, they will appear in the terminal whenever an assertion fails.

Does that help?

**Comment by mmellado** [comment]
Ah! It all makes sense now, thanks a lot for clarifying!

**Comment by mmellado** [comment]
BTW, it would be nice if you could add a brief description of the API in the README. For people who are already experienced in unit testing, this might be a bit more obvious, but it wouldn't be for people who are just experimenting and playing around with it to learn ;)

**Comment by mirisuzanne** [comment]
That's a great idea. Do you want to make a pull request? :)
